version: "3.8"

services:
  # Database Service
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress-network

  # WordPress Service
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-network
    volumes:
      - ./wp-content:/var/www/html/wp-content

  # PHPMyAdmin Service
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80" # Map port 80 of the container to port 8080 on host
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password # Specify the root password of your MySQL/MariaDB instance
    networks:
      - wordpress-network
    volumes:
      - /sessions # Optional: You can define a volume for session data if needed

volumes:
  db_data: {}

networks:
  wordpress-network:
    driver: bridge
